// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCGfKt8tBjf98msx0RUVkcDhT9qsib6iw',
    appId: '1:944435469157:android:cfa4c074c486c720cd9f8c',
    messagingSenderId: '944435469157',
    projectId: 'fir-auth-boilerplate-a6e81',
    storageBucket: 'fir-auth-boilerplate-a6e81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFNvHkp78b-DjlZ2lg8fKqBpq2KcMuwOA',
    appId: '1:944435469157:ios:21414c529d719a76cd9f8c',
    messagingSenderId: '944435469157',
    projectId: 'fir-auth-boilerplate-a6e81',
    storageBucket: 'fir-auth-boilerplate-a6e81.appspot.com',
    androidClientId: '944435469157-vi8plhp4en1n13febg6uphokb2dp7s7p.apps.googleusercontent.com',
    iosClientId: '944435469157-2f53f63stsqd045jo3a2gnu6ki54icnt.apps.googleusercontent.com',
    iosBundleId: 'com.example.authBoilerplate',
  );
}
